apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: chameleon-volume
  nfs:
    server: 192.168.1.11  # node1 private IP
    path: /mnt/persistent/minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: platform
spec:
  storageClassName: chameleon-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
